### ISSUE TITLE
Security Hub Finding doesn't get written

### ISSUE THREAD

**Issue by rjjaegeraws** [aws-samples/aws-container-devsecops-workshop#6]
When starting fresh and following the guide step-by-step, the Vulnerability entry does not get entered into the Security Hub.

In the buildspec_vuln.yml file the first post build step:
- $ANCHORE_CMD image add $IMAGE
fails with the following message: Error: cannot fetch image digest/manifest from registry

This build step fails:
docker build $CODEBUILD_SRC_DIR_AppSource -t $IMAGE
...
...
ERROR: unsatisfiable constraints:
  sqlite-libs-3.28.0-r0:
    breaks: world[sqlite-libs=3.26.0-r3]
    satisfies: .python-rundeps-20190821.002138[so:libsqlite3.so.0]

Because this fails, the image isn't pushed to the repository which causes the post build to fail.

**Comment by nickksun** [comment]
Reason is that apk command does not return success since this version of sqlite-libs will cause `ERROR: unsatisfiable constraints` during `docker build`

**Comment by alanoberto** [comment]
@rjjaegeraws  could you solve this?

**Comment by rjjaegeraws** [comment]
> @rjjaegeraws could you solve this?

No, never went deeper into solving it.

**Comment by umairishaq** [comment]
@alanoberto, @rjjaegeraws we added a step in the "Pipeline Testing" module to address this issue of unavailable dependency, stating: "Update the version for sqlite-libs to 3.30.1-r1". This should get you past that particular error. We are also working on updating content so this issue goes away.

**Comment by alanoberto** [comment]
@umairishaq I change it and run but does not find any vulnerabilities!!

**Comment by umairishaq** [comment]
The alpine packaging system seems to discard old versions of packages. I see that a new version was published, 3.32.1-r0, at https://pkgs.alpinelinux.org/package/edge/main/x86/sqlite-libs. I'll update the content to fix it. Also, the vulnerable package, 2.26 was supposed to showcase the vulnerability. Since it is also not available in the official repo, I'll work to have it pulled from a private repo for the workshop. @alanoberto would you try building with 3.32.1-r0?

**Comment by alanoberto** [comment]
Hi @umairishaq just tested version 3.30.1-r2 and did work. However, the system is not finding vulnerabilities:

**[Container] 2020/05/29 18:11:39 Running command $ANCHORE_CMD image add $IMAGE**
--
361 | Image Digest: sha256:f325404e5d4b6f96fa55567feec83053fddef4d50010d5fad68b750ea45927b5
362 | Parent Digest: sha256:f325404e5d4b6f96fa55567feec83053fddef4d50010d5fad68b750ea45927b5
363 | Analysis Status: not_analyzed
364 | Image Type: docker
365 | Image ID: f3539314c936d201a4dbcd7351442602fa9ec1b6eec88d40fa40462c05f14f97
366 | Dockerfile Mode: None
367 | Distro: None
368 | Distro Version: None
369 | Size: None
370 | Architecture: None
371 | Layer Count: None
372 |  
373 | Full Tag: 799305811635.dkr.ecr.us-east-2.amazonaws.com/container-devsecops-sample:latest
374 |  
375 |  
376 |  
**377 | [Container] 2020/05/29 18:11:40 Running command while [ $($ANCHORE_CMD --json image get $IMAGE \| jq -r '.[0].analysis_status') != "analyzed" ]; do sleep 1; done**
378 |  
**379 | [Container] 2020/05/29 18:12:10 Running command $ANCHORE_CMD --json image vuln $IMAGE os > scan_results.json**
380 |  
**381 | [Container] 2020/05/29 18:12:11 Running command cat scan_results.json**
382 | {
383 | "imageDigest": "sha256:f325404e5d4b6f96fa55567feec83053fddef4d50010d5fad68b750ea45927b5",
384 | "vulnerabilities": [],
385 | "vulnerability_type": "os"
386 | }



[Container] 2020/05/29 18:11:39 Running command $ANCHORE_CMD image add $IMAGE
--
361 | Image Digest: sha256:f325404e5d4b6f96fa55567feec83053fddef4d50010d5fad68b750ea45927b5
362 | Parent Digest: sha256:f325404e5d4b6f96fa55567feec83053fddef4d50010d5fad68b750ea45927b5
363 | Analysis Status: not_analyzed
364 | Image Type: docker
365 | Image ID: f3539314c936d201a4dbcd7351442602fa9ec1b6eec88d40fa40462c05f14f97
366 | Dockerfile Mode: None
367 | Distro: None
368 | Distro Version: None
369 | Size: None
370 | Architecture: None
371 | Layer Count: None
372 |  
373 | Full Tag: 799305811635.dkr.ecr.us-east-2.amazonaws.com/container-devsecops-sample:latest
374 |  
375 |  
376 |  
377 | [Container] 2020/05/29 18:11:40 Running command while [ $($ANCHORE_CMD --json image get $IMAGE \| jq -r '.[0].analysis_status') != "analyzed" ]; do sleep 1; done
378 |  
379 | [Container] 2020/05/29 18:12:10 Running command $ANCHORE_CMD --json image vuln $IMAGE os > scan_results.json
380 |  
381 | [Container] 2020/05/29 18:12:11 Running command cat scan_results.json
382 | {
383 | "imageDigest": "sha256:f325404e5d4b6f96fa55567feec83053fddef4d50010d5fad68b750ea45927b5",
384 | "vulnerabilities": [],
385 | "vulnerability_type": "os"
386 | }


[Container] 2020/05/29 18:11:39 Running command $ANCHORE_CMD image add $IMAGE
--
361 | Image Digest: sha256:f325404e5d4b6f96fa55567feec83053fddef4d50010d5fad68b750ea45927b5
362 | Parent Digest: sha256:f325404e5d4b6f96fa55567feec83053fddef4d50010d5fad68b750ea45927b5
363 | Analysis Status: not_analyzed
364 | Image Type: docker
365 | Image ID: f3539314c936d201a4dbcd7351442602fa9ec1b6eec88d40fa40462c05f14f97
366 | Dockerfile Mode: None
367 | Distro: None
368 | Distro Version: None
369 | Size: None
370 | Architecture: None
371 | Layer Count: None
372 |  
373 | Full Tag: 799305811635.dkr.ecr.us-east-2.amazonaws.com/container-devsecops-sample:latest
374 |  
375 |  
376 |  
377 | [Container] 2020/05/29 18:11:40 Running command while [ $($ANCHORE_CMD --json image get $IMAGE \| jq -r '.[0].analysis_status') != "analyzed" ]; do sleep 1; done
378 |  
379 | [Container] 2020/05/29 18:12:10 Running command $ANCHORE_CMD --json image vuln $IMAGE os > scan_results.json
380 |  
381 | [Container] 2020/05/29 18:12:11 Running command cat scan_results.json
382 | {
383 | "imageDigest": "sha256:f325404e5d4b6f96fa55567feec83053fddef4d50010d5fad68b750ea45927b5",
384 | "vulnerabilities": [],
385 | "vulnerability_type": "os"
386 | }


[Container] 2020/05/29 18:11:39 Running command $ANCHORE_CMD image add $IMAGE
--
361 | Image Digest: sha256:f325404e5d4b6f96fa55567feec83053fddef4d50010d5fad68b750ea45927b5
362 | Parent Digest: sha256:f325404e5d4b6f96fa55567feec83053fddef4d50010d5fad68b750ea45927b5
363 | Analysis Status: not_analyzed
364 | Image Type: docker
365 | Image ID: f3539314c936d201a4dbcd7351442602fa9ec1b6eec88d40fa40462c05f14f97
366 | Dockerfile Mode: None
367 | Distro: None
368 | Distro Version: None
369 | Size: None
370 | Architecture: None
371 | Layer Count: None
372 |  
373 | Full Tag: 799305811635.dkr.ecr.us-east-2.amazonaws.com/container-devsecops-sample:latest
374 |  
375 |  
376 |  
377 | [Container] 2020/05/29 18:11:40 Running command while [ $($ANCHORE_CMD --json image get $IMAGE \| jq -r '.[0].analysis_status') != "analyzed" ]; do sleep 1; done
378 |  
379 | [Container] 2020/05/29 18:12:10 Running command $ANCHORE_CMD --json image vuln $IMAGE os > scan_results.json
380 |  
381 | [Container] 2020/05/29 18:12:11 Running command cat scan_results.json
382 | {
383 | "imageDigest": "sha256:f325404e5d4b6f96fa55567feec83053fddef4d50010d5fad68b750ea45927b5",
384 | "vulnerabilities": [],
385 | "vulnerability_type": "os"
386 | }

**Comment by andrew-canning** [comment]
I have a pull request that may solve this.

Essentially by updating the Anchore version (to 0.8.2) and switching to check for bad python packages, we can get the same effect. 

As stated before, Alpine tends to remove older packages; especially when they have know vulnerabilities behind them.  By using an old 'flask-cors' version(3.0.8) we can get Anchore to report a vulnerability with "high" severity. 

You can still get that old sqlite version in Alpine 3.4, however Anchore reports it as a "medium" severity (probably gets that from the Debian security tracker).  

Anchore needs to be updated because we are going to use the nvd2 feed to detect the python package issues.

**Comment by umairishaq** [comment]
With [PR 11](https://github.com/aws-samples/aws-container-devsecops-workshop/pull/11), the issue has been fixed. Closing it.
