### ISSUE TITLE
Workshop is broken due to issue with Trufflehog dependency

### ISSUE THREAD

**Issue by umairishaq** [aws-samples/aws-container-devsecops-workshop#8]
Due to a recent update to gitdb(a dependency of Trufflehog), the secrets scanning step breaks on `pip install trufflehog`. For reference, please, see [gitdb update breaks trufflehog #200](https://github.com/dxa4481/truffleHog/issues/200) for details.

**Comment by umairishaq** [comment]
Fixed with https://github.com/aws-samples/aws-container-devsecops-workshop/pull/9.

**Comment by jmfuchs** [comment]
Merged fix.
